#!/bin/bash

# Enable suspend-then-hibernate
rm /usr/lib/systemd/system/systemd-suspend.service;
ln -s /usr/lib/systemd/system/systemd-suspend-then-hibernate.service /usr/lib/systemd/system/systemd-suspend.service;
