#!/bin/bash
tablet="$(awk '{print substr($0,0,3);}' /sys/class/dmi/id/bios_version)"
tablet2="$(dmidecode -s system-manufacturer | head -1)"

# GRUB

case "$tablet2" in
     Digitek)
     sed -i -e '/GRUB_CMDLINE_LINUX_DEFAULT/d' /etc/default/grub;
     sed -i '/\GRUB_DISTRIBUTOR/a GRUB_CMDLINE_LINUX_DEFAULT="quiet splash i8042.nopnp pcie_port_pm=off"' /etc/default/grub
     update-grub
     ;;
esac

# Flatpak
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

# Recopy HiFi.conf to ucm2
case "$tablet" in
     JP2)
     rm /usr/share/alsa/ucm2/Intel/sof-essx8336/HiFi.conf;
     cp /usr/share/suspend-then-hibernate/HiFi.conf /usr/share/alsa/ucm2/Intel/sof-essx8336/;
     alsaucm reload
     ;;
esac     

# Disable Suspend and replace it with Suspend-then-Hibernate
rm /usr/lib/systemd/system/systemd-suspend.service
ln -s /usr/lib/systemd/system/systemd-suspend-then-hibernate.service /usr/lib/systemd/system/systemd-suspend.service

# Enable Systemd services
systemctl enable powertop
systemctl start powertop
systemctl enable juno-pp
systemctl enable juno-kd
systemctl enable upower

# Reload systemd for suspend-then-hibernate
systemctl daemon-reload
systemctl stop powertop
systemctl start powertop

# Update initramfs
update-initramfs -u -k all

# Update schemas
glib-compile-schemas /usr/share/glib-2.0/schemas/

# Update systemd
systemd-hwdb update
udevadm trigger -v -p DEVNAME=/dev/iio:device0
udevadm control --reload
udevadm trigger

updatedb

# Remove non-free from sources.list
sed -i 's/non-free-firmware//g' /etc/apt/sources.list
sed -i 's/non-free//g' /etc/apt/sources.list
sed -i 's/contrib//g' /etc/apt/sources.list

echo "Please restart tablet for updated packages to take effect"

