#!/bin/bash

# Set chassis to handset
#hostnamectl set-chassis handset
#cat /etc/machine-info

# GRUB
#sed -i -e '/GRUB_TIMEOUT/d' /etc/default/grub
#sed -i '/\GRUB_DEFAULT/a GRUB_TIMEOUT=0' /etc/default/grub
#sed -i -e '/GRUB_TIMEOUT_STYLE/d' /etc/default/grub
#sed -i '/\GRUB_TIMEOUT/a GRUB_TIMEOUT_STYLE=hidden' /etc/default/grub
sed -i -e '/GRUB_CMDLINE_LINUX_DEFAULT/d' /etc/default/grub
sed -i '/\GRUB_DISTRIBUTOR/a GRUB_CMDLINE_LINUX_DEFAULT="quiet splash mem_sleep_default=s2idle"' /etc/default/grub
update-grub

#hostnamectl set-chassis handset

# Flatpak
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

# Recopy HiFi.conf to ucm2
rm /usr/share/alsa/ucm2/Intel/sof-essx8336/HiFi.conf;
cp /usr/share/suspend-then-hibernate/HiFi.conf /usr/share/alsa/ucm2/Intel/sof-essx8336/;
alsaucm reload

# Disable Suspend and replace it with Suspend-then-Hibernate
rm /usr/lib/systemd/system/systemd-suspend.service
ln -s /usr/lib/systemd/system/systemd-suspend-then-hibernate.service /usr/lib/systemd/system/systemd-suspend.service

# Enable Systemd services
systemctl enable powertop
systemctl start powertop
#systemctl enable powertop-usb-mouse
#systemctl start powertop-usb-mouse
systemctl enable juno-pp
systemctl enable juno-kd

# Reload systemd for suspend-then-hibernate
systemctl daemon-reload
systemctl stop powertop
systemctl start powertop

# Enable suspend-then-hibernate in logind.conf
#sed -i -e '/HandleLidSwitch/d' /etc/systemd/logind.conf
#sed -i '/\#HandleHibernateKey=hibernate/a HandleLidSwitch=suspend-then-hibernate' /etc/systemd/logind.conf

# Hibernate starts in 5 minutes after suspend
#sed -i -e '/HibernateDelaySec/d' /etc/systemd/sleep.conf
#sed -i '/\#HybridSleepState/a HibernateDelaySec=300s' /etc/systemd/sleep.conf

# Update initramfs
update-initramfs -u -k all

# Update schemas
glib-compile-schemas /usr/share/glib-2.0/schemas/

# Update systemd
systemd-hwdb update
udevadm trigger -v -p DEVNAME=/dev/iio:device0
udevadm control --reload
udevadm trigger

updatedb

# Remove non-free from sources.list
sed -i 's/non-free-firmware//g' /etc/apt/sources.list
sed -i 's/non-free//g' /etc/apt/sources.list
sed -i 's/contrib//g' /etc/apt/sources.list

echo "Please restart tablet for updated packages to take effect"

